### ISSUE TITLE
 library not found for -lRNSpeechToTextIos

### ISSUE THREAD

**Issue by spoeck** [innFactory/react-native-dialogflow#17]
Issue of @Arafath-misree

> Guys does this support latest version of react-native i am getting an error ld: library not found for -lRNSpeechToTextIos
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by spoeck** [comment]
@Arafath-misree
Do you have further information? Which react-native version do you use?

**Comment by jamesdabbs** [comment]
I just scaffolded up a new project (create-react-native-app > eject) and am having this issue as well. React Native 0.48.4.

I'm new to this who ecosystem, but let me know if I can do anything to help track down / reproduce the issue.

**Comment by jamesdabbs** [comment]
Update: I manually linked in the `RNSpeechToTextIos` library (following the directions from https://facebook.github.io/react-native/docs/linking-libraries-ios.html) and it's working fine now.

**Comment by spoeck** [comment]
Tnanks for your update. I added the linking step for `react-native-speech-to-text-ios` in the redme.
