### ISSUE TITLE
Offline Speech recognition

### ISSUE THREAD

**Issue by aamping** [innFactory/react-native-dialogflow#20]
Hi,

I am working in an app and I first need a speech recognition without network.

Does react-native-dialogflow component can work offline, for the recognition part only?

I tested it and it keeps popping network error when I try offline on my AVD.

Any thoughts?

Thanks

**Comment by spoeck** [comment]
Hey,

if you want to recognize the speech offline without any dialogflow you will need the native speech-to-text functions. You can use `react-native-speech-to-text-ios` for ios as example.
