### ISSUE TITLE
Android Pixel 2 - Unable to invoke requestQueryNative

### ISSUE THREAD

**Issue by barbaragomes** [innFactory/react-native-dialogflow#21]
I only got this error when the app is running on Pixel Phone and that is all I see:

`Unable to invoke requestQueryNative`

Running on debug mode I caught the exception:

`java.lang.NoClassDefFoundError: ai.api.android.AIDataService`

Any suggestions?

**UPDATE**: Pixel phone is the only device that is running Android 8

**Comment by Taroka** [comment]
Hi I cannot run the example and cannot integrate the package with my project. Could you tell me your experience about using this package? I thought the DialogFlow remove the speech to text function.

**Comment by barbaragomes** [comment]
Hey,

I have fixed this issue.
The problem only happened on devices that runs Android 8.

I had to change the dependency list for the api.ai library.

Now it works on all android versions

**Comment by spoeck** [comment]
Hey @barbaragomes, Thank for your issue and also your solution!

Could you post the changes on the dependency list you made on the api.ai library?

> The problem only happened on devices that runs Android 8.

Seems that now I have a reason to by a new Android Phone :D

**Comment by barbaragomes** [comment]
I had to fix two things actually:

1 - Dependency list for Android 8

2 - The context was being set wrongly

I will create a PR for both

**Comment by spoeck** [comment]
@barbaragomes 
Thanks for your pull request and sorry for my late reply/merge!
