### ISSUE TITLE
Invalid authentication

### ISSUE THREAD

**Issue by akrupych-remit** [innFactory/react-native-dialogflow#36]
Hi, I'm trying to query my Dialogflow model using Dialogflow_V2:
```
  constructor(props) {
    super(props);
    Dialogflow_V2.setConfiguration(
      "***@***.iam.gserviceaccount.com",
      "-----BEGIN PRIVATE KEY-----***\n-----END PRIVATE KEY-----\n",
      Dialogflow_V2.LANG_EN,
      "***"
    );
  }

  requestQuery = () => {
    Dialogflow_V2.requestQuery(
      "Hello",
      result => this.setState({
        result: JSON.stringify(result)
      }),
      error => this.setState({
        error: JSON.stringify(error)
      })
    );
  }

  render() {
    return (
      <View style={styles.container}>
        <Button title="Hello" onPress={this.requestQuery}/>
        <Text>Result: {this.state.result}</Text>
        <Text>Error: {this.state.error}</Text>
        <Text>Access Token: {Dialogflow_V2.accessToken}</Text>
      </View>
    );
  }
```
And I get 401 error code and seems accessToken is undefined:
![image](https://user-images.githubusercontent.com/17251879/41652761-b55efbfa-748c-11e8-8823-fe24c196188e.png)

Tried to debug Dialogflow_V2.requestQuery call, but I'm always getting red screen before reaching breakpoint:
![image](https://user-images.githubusercontent.com/17251879/41652999-7327bb72-748d-11e8-958a-4fe30246eae1.png)

Not sure if this is really connected with your library, but guys, can you help me sort this out?

**Comment by spoeck** [comment]
@akrupych-remit 
I think it was my fault. I made some fixes. Can you try to delete your node_modls/react-native-dialogflow folder and install it again via:
`npm i --save 'https://github.com/innFactory/react-native-dialogflow/issues/36'

**Comment by akrupych-remit** [comment]
Thanks for the fix, but still undefined accessToken.

**Comment by spoeck** [comment]
@akrupych-remit 
found another bug, now it definitely should work. Can you please test it again?

**Comment by akrupych-remit** [comment]
Great, thanks! But now language code is not specified:)

![simulator screen shot - iphone 6 - 2018-06-20 at 17 29 48](https://user-images.githubusercontent.com/17251879/41665270-40065334-74b0-11e8-91c7-2e55b365418b.png)

**Comment by spoeck** [comment]
Thank you too for reviewing/testing!

Now you can use the version `3.1.1`. Don't forget to change your package.json and handle the dependencies via npm versions and not via the github master branch.
Or just run `npm i --save react-native-dialogflow` again.

**Comment by akrupych-remit** [comment]
Authentication doesn't work for me again :(
Using 3.1.3:
```
  import dialogflowConfig from './<projectId>-cbb34806af4f.json'

  initDialogflow() {
    Dialogflow_V2.setConfiguration(
      dialogflowConfig.client_email,
      dialogflowConfig.private_key,
      Dialogflow_V2.LANG_ENGLISH,
      dialogflowConfig.project_id
    );

    Dialogflow_V2.requestQuery(
      "hi",
      result => console.log("Dialogflow result:", JSON.stringify(result), 'Access token:', Dialogflow_V2.accessToken),
      error => console.log("Dialogflow error request: " + JSON.stringify(error))
    );
  }
```

This time access token is not empty, but still 401:
`Dialogflow result: {"error":{"code":401,"message":"Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.","status":"UNAUTHENTICATED"}} Access token: ya29.c.Elr2BVKFvWAWHkusM8PRaE8qVokLkfZllKvteCJeDbM1ooBaYTs3m_-P94NIgsUaHIP9SY3YQsFYqNgKPSW66fUWjBfpYfN9hhfUMn42p5F-zDEgNgUcm8ligfA`

**Comment by akrupych-remit** [comment]
UPD: my fault, called requestQuery too early. Works when calling from componentDidMount(). Would be nice to understand this from logs though. Closing this one.

**Comment by gsevla** [comment]
Always getting UNAUTHENTICATED. I'm using as example:

```
import { Dialogflow_V2 } from "react-native-dialogflow";
import dialogflowConfig from './src/<project-id>-c2c8397623f0';

initDialogflow() {
    Dialogflow_V2.setConfiguration(
      dialogflowConfig.client_email,
      dialogflowConfig.private_key,
      Dialogflow_V2.LANG_ENGLISH,
      dialogflowConfig.project_id
    );
  }

  constructor(props) {
    super(props);
    this.state = {
      result: "",
      listeningState: "not started",
      audioLevel: 0,
    };

    this.initDialogflow();
  }
```

In render(), the first thing is:
`Dialogflow_V2.requestEvent("WELCOME", null, r => console.log(r), e => console.log(e));`

When i check in console:
> error:
> code: 401
> message: "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project."
> status: "UNAUTHENTICATED"

I'm using:
**react-native-voice@0.2.6
react-native-dialogflow@3.2.2**

**Comment by Baksha2008** [comment]
I had the same problem. For me, the solution was to add async / await before the request!
