### ISSUE TITLE
Android Listeners always trigger instantly

### ISSUE THREAD

**Issue by chrisroe** [innFactory/react-native-dialogflow#42]
The `onListeningCanceled `and `onListeningFinished` callbacks trigger instantly.
The listeners are set before each `startListening` call and I am using V2. I am getting the desired results from `startListening`. There is another problem with `startListening` not removing the listener after the result is passed, see [this issue here](https://github.com/innFactory/react-native-dialogflow/issues/39)

Thank you for your time,
Chris

**Comment by spoeck** [comment]
Thanks for reporting the issue.
Should be fixed with `v3.2.0`
