### ISSUE TITLE
Dialogflow_V2 init failed:malformed plain PKCS8 private key(code:001)

### ISSUE THREAD

**Issue by jasonmerino** [innFactory/react-native-dialogflow#44]
I am having trouble using the `Dialogflow_V2.setConfiguration` method. I set it up the same as the example on the README and replaced the values with my values but I'm getting this error message.

`init failed:malformed plain PKCS8 private key(code:001)`

![iphone_8_-_11_3__15e217_](https://user-images.githubusercontent.com/1660279/43219908-7c2f6216-8ffd-11e8-855e-e2925b0b6be6.png)

I assume that is talking about the second argument that is formatted this way:

```
-----BEGIN PRIVATE KEY-----\n***\n-----END PRIVATE KEY-----\n
```

Strange thing is, when I change it so that value is just the value in `***` it gives me this error:

```
init failed:not supported argument
```

![banners_and_alerts_and_iphone_8_-_11_3__15e217_](https://user-images.githubusercontent.com/1660279/43220089-f504c5aa-8ffd-11e8-9405-ea7abcac5b56.png)

It's not really clear by these error messages as to what is going on. Any help would be very nice. Thanks!

**Comment by sibelius** [comment]
change `\\n` to `\n`

**Comment by AlcuinGuest** [comment]
@jasonmerino Did you solve this? Having the same problem.

**Comment by jasonmerino** [comment]
@AlcuinGuest glad you were able to solve it!
