### ISSUE TITLE
Dialogflow voice gives more than one response

### ISSUE THREAD

**Issue by JaiKishan911** [innFactory/react-native-dialogflow#45]
While trying out the Dialogflow voice to text in react native i got more than one response with different response Id. Not sure what is causing this. 
for second request i got 2 responses..
for third it was 3..and so on.

**Comment by gunslingerfry** [comment]
See: https://github.com/innFactory/react-native-dialogflow/issues/39

I posted a temp solution, but @spoeck says it will be fixed in the next release.

**Comment by gunslingerfry** [comment]
New version was put up (but not released on github). https://www.npmjs.com/package/react-native-dialogflow
