### ISSUE TITLE
clang: error: no such file or directory libApiAi.a

### ISSUE THREAD

**Issue by sibelius** [innFactory/react-native-dialogflow#54]
clang: error: no such file or directory: '/Users/sibelius/Library/Developer/Xcode/DerivedData/app-fqlxmqrhtgfyvwfopwgfyrnexuva/Build/Intermediates.noindex/ArchiveIntermediates/app/BuildProductsPath/Release-iphoneos/libApiAi.a'

**Comment by spoeck** [comment]
could you try `react-native link react-native-dialogflow`?

**Comment by sibelius** [comment]
fixed removing libApiAi.a from link, not sure why

but as we don't need the iOS bridge, it is all good
